### ISSUE TITLE
Handling multiple baseURLs and multiple versions of a module

### ISSUE THREAD

**Issue by Jakobo** [linkedin/inject#287]
These ideas are based on http://jspm.io/

One of the challenges LinkedIn currently faces is modules that come from multiple locations. For example, if your app depends on the "global" jquery, you want to specify your origin at the front of the string. This would allow for more than one base path. While RequireJS allows for multiple context objects (as does Inject technically), there really should be a cleaner solution.

The second challenge we're looking at is how to support versioning. Upgrading a shared library shouldn't force all dependencies to auto-update, especially if there is a breaking change.

JSPM solves this using the following syntax

```
origin:module/path#x.y.z
```

However, this isn't really compatible with the AMD standard.

There is a plugin developed by @guybedford at https://github.com/guybedford/amd-version but right in the readme it says this is a terrible idea.

**Comment by thecodedrift** [comment]
Going to close this, as folks should be using [SystemJS](https://github.com/systemjs/systemjs) if they have a hard requirement on runtime loading, or Webpack/Rollup/Parcel/Broccoli/etc if they're comfortable with the bundling, tree shaking, and dynamic loading those packagers provide.
