### ISSUE TITLE
bower.json "main" files for LICENSE, README, and relay.html are wrong

### ISSUE THREAD

**Issue by lambertsteven** [linkedin/inject#312]
In the `bower.json`, you list `dist/LICENSE`, `dist/README.md`, and `dist/relay.html`. The paths are incorrect and should point to the `dist/recent` folder for each of them. I was trying to use these paths to load the files but couldn't since they don't exist at those paths.

On a side note, the README is saved as `README.markdown` not `README.md`

**Comment by Jakobo** [comment]
Thanks @lambertsteven I'll get those fixed up.

**Comment by Jakobo** [comment]
Resolved in HEAD, and also 0.7.2 pushed out to bower. Thanks for catching those.

**Comment by lambertsteven** [comment]
Awesome, thanks for fixing that so quickly.
